// ===== Mock 数据 - MVP 演示用（覆盖小学→初中→高中） =====
import type { AncientText, StudyTask, LearningStats, ReadingRecord, User, LessonPlan, TeachingStats, StudyPoint, TieredContent } from '../types';

// ---- 用户 ----
export const mockUsers: Record<string, User> = {
  student: {
    id: 'student-001',
    name: '小探宝',
    role: 'student',
    grade: 5,
    schoolStage: 'primary',
  },
  teacher: {
    id: 'teacher-001',
    name: '张老师',
    role: 'teacher',
    subject: '语文',
    school: '杭州市实验小学',
  },
  independentTeacher: {
    id: 'teacher-002',
    name: '李老师',
    role: 'teacher',
    subject: '语文/国学',
    school: '独立教师',
  },
  librarian: {
    id: 'lib-001',
    name: '王馆长',
    role: 'librarian',
  },
};

export const mockUser: User = mockUsers.student;

// ---- 古籍列表（扩展至初高中） ----
export const mockTexts: AncientText[] = [
  // === 小学段 ===
  {
    id: 'text-001',
    title: '静夜思',
    author: '李白',
    dynasty: '唐',
    cadalId: 'CADAL-2024001',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=静夜思·古籍原图',
    gradeLevel: [1],
    schoolStage: ['primary'],
    tags: ['唐诗', '思乡', '李白'],
    difficulty: 1,
    textbookMatch: [
      { grade: 1, semester: '下', unit: '第四单元', lessonName: '静夜思', knowledgePoints: ['五言绝句', '思乡之情', '比喻手法'] },
    ],
  },
  {
    id: 'text-002',
    title: '三字经（节选）',
    author: '王应麟',
    dynasty: '宋',
    cadalId: 'CADAL-2024002',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=三字经·古籍原图',
    gradeLevel: [1],
    schoolStage: ['primary'],
    tags: ['蒙学', '三字经', '启蒙'],
    difficulty: 1,
    textbookMatch: [
      { grade: 1, semester: '下', unit: '识字单元', lessonName: '人之初', knowledgePoints: ['三字韵文', '传统美德', '勤学故事'] },
    ],
  },
  {
    id: 'text-003',
    title: '守株待兔',
    author: '韩非',
    dynasty: '战国',
    cadalId: 'CADAL-2024003',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=韩非子·古籍原图',
    gradeLevel: [3, 4],
    schoolStage: ['primary'],
    tags: ['文言文', '寓言', '成语'],
    difficulty: 2,
    textbookMatch: [
      { grade: 3, semester: '下', unit: '第二单元', lessonName: '寓言二则', knowledgePoints: ['文言虚词', '寓言寓意', '成语来源'] },
    ],
  },
  {
    id: 'text-004',
    title: '观书有感',
    author: '朱熹',
    dynasty: '宋',
    cadalId: 'CADAL-2024004',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=观书有感·古籍原图',
    gradeLevel: [5],
    schoolStage: ['primary'],
    tags: ['宋诗', '哲理', '读书'],
    difficulty: 2,
    textbookMatch: [
      { grade: 5, semester: '上', unit: '第八单元', lessonName: '观书有感', knowledgePoints: ['七言绝句', '比喻说理', '借景喻理'] },
    ],
  },
  {
    id: 'text-006',
    title: '望庐山瀑布',
    author: '李白',
    dynasty: '唐',
    cadalId: 'CADAL-2024006',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=望庐山瀑布·古籍原图',
    gradeLevel: [2],
    schoolStage: ['primary'],
    tags: ['唐诗', '山水', '李白'],
    difficulty: 1,
    textbookMatch: [
      { grade: 2, semester: '上', unit: '第四单元', lessonName: '古诗二首', knowledgePoints: ['七言绝句', '夸张手法', '景物描写'] },
    ],
  },
  {
    id: 'text-025',
    title: '春晓',
    author: '孟浩然',
    dynasty: '唐',
    cadalId: 'CADAL-2024025',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=春晓·古籍原图',
    gradeLevel: [1],
    schoolStage: ['primary'],
    tags: ['唐诗', '春天', '孟浩然', '写景'],
    difficulty: 1,
    textbookMatch: [
      { grade: 1, semester: '下', unit: '课文', lessonName: '春晓', knowledgePoints: ['五言绝句', '春日晨景', '惜春之情'] },
    ],
  },
  {
    id: 'text-026',
    title: '咏柳',
    author: '贺知章',
    dynasty: '唐',
    cadalId: 'CADAL-2024026',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=咏柳·古籍原图',
    gradeLevel: [2],
    schoolStage: ['primary'],
    tags: ['唐诗', '春天', '贺知章', '咏物'],
    difficulty: 1,
    textbookMatch: [
      { grade: 2, semester: '下', unit: '第一单元', lessonName: '古诗二首', knowledgePoints: ['七言绝句', '比喻手法', '咏物诗'] },
    ],
  },
  {
    id: 'text-027',
    title: '池上',
    author: '白居易',
    dynasty: '唐',
    cadalId: 'CADAL-2024027',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=池上·古籍原图',
    gradeLevel: [1],
    schoolStage: ['primary'],
    tags: ['唐诗', '童趣', '白居易', '写景'],
    difficulty: 1,
    textbookMatch: [
      { grade: 1, semester: '下', unit: '古诗二首', lessonName: '池上', knowledgePoints: ['五言绝句', '童趣', '动作描写'] },
    ],
  },
  {
    id: 'text-028',
    title: '小池',
    author: '杨万里',
    dynasty: '宋',
    cadalId: 'CADAL-2024028',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=小池·古籍原图',
    gradeLevel: [1],
    schoolStage: ['primary'],
    tags: ['宋诗', '夏天', '杨万里', '写景'],
    difficulty: 1,
    textbookMatch: [
      { grade: 1, semester: '下', unit: '古诗二首', lessonName: '小池', knowledgePoints: ['七言绝句', '初夏小景', '细腻观察'] },
    ],
  },
  {
    id: 'text-029',
    title: '村居',
    author: '高鼎',
    dynasty: '清',
    cadalId: 'CADAL-2024029',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=村居·古籍原图',
    gradeLevel: [2],
    schoolStage: ['primary'],
    tags: ['清诗', '春天', '高鼎', '童趣'],
    difficulty: 1,
    textbookMatch: [
      { grade: 2, semester: '下', unit: '第一单元', lessonName: '古诗二首', knowledgePoints: ['七言绝句', '春日乡村', '童趣'] },
    ],
  },

  // === 初中段 ===
  {
    id: 'text-007',
    title: '岳阳楼记',
    author: '范仲淹',
    dynasty: '宋',
    cadalId: 'CADAL-2024007',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=岳阳楼记·古籍原图',
    gradeLevel: [8, 9],
    schoolStage: ['junior'],
    tags: ['文言文', '游记', '名篇'],
    difficulty: 3,
    textbookMatch: [
      { grade: 8, semester: '下', unit: '第六单元', lessonName: '岳阳楼记', knowledgePoints: ['文言虚词', '景物描写', '先忧后乐思想', '骈散结合'] },
    ],
  },
  {
    id: 'text-008',
    title: '出师表',
    author: '诸葛亮',
    dynasty: '三国',
    cadalId: 'CADAL-2024008',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=出师表·古籍原图',
    gradeLevel: [9],
    schoolStage: ['junior'],
    tags: ['文言文', '奏表', '名篇'],
    difficulty: 4,
    textbookMatch: [
      { grade: 9, semester: '下', unit: '第五单元', lessonName: '出师表', knowledgePoints: ['文言实词', '议论抒情', '忠君爱国', '古今异义'] },
    ],
  },
  {
    id: 'text-009',
    title: '桃花源记',
    author: '陶渊明',
    dynasty: '东晋',
    cadalId: 'CADAL-2024009',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=桃花源记·古籍原图',
    gradeLevel: [8],
    schoolStage: ['junior'],
    tags: ['文言文', '游记', '理想社会'],
    difficulty: 3,
    textbookMatch: [
      { grade: 8, semester: '上', unit: '第三单元', lessonName: '桃花源记', knowledgePoints: ['叙事结构', '环境描写', '社会理想'] },
    ],
  },

  // === 高中段 ===
  {
    id: 'text-010',
    title: '赤壁赋',
    author: '苏轼',
    dynasty: '宋',
    cadalId: 'CADAL-2024010',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=赤壁赋·古籍原图',
    gradeLevel: [10],
    schoolStage: ['senior'],
    tags: ['文言文', '赋', '哲理', '苏轼'],
    difficulty: 5,
    textbookMatch: [
      { grade: 10, semester: '上', unit: '第三单元', lessonName: '赤壁赋', knowledgePoints: ['赋体特点', '主客问答', '变与不变的哲理', '景情理融合'] },
    ],
  },
  {
    id: 'text-011',
    title: '劝学',
    author: '荀子',
    dynasty: '战国',
    cadalId: 'CADAL-2024011',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=劝学·古籍原图',
    gradeLevel: [10],
    schoolStage: ['senior'],
    tags: ['文言文', '议论', '学习'],
    difficulty: 4,
    textbookMatch: [
      { grade: 10, semester: '上', unit: '第二单元', lessonName: '劝学', knowledgePoints: ['比喻论证', '对比论证', '文言虚词"而"的用法'] },
    ],
  },
  {
    id: 'text-012',
    title: '师说',
    author: '韩愈',
    dynasty: '唐',
    cadalId: 'CADAL-2024012',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=师说·古籍原图',
    gradeLevel: [10, 11],
    schoolStage: ['senior'],
    tags: ['文言文', '议论', '教育'],
    difficulty: 4,
    textbookMatch: [
      { grade: 10, semester: '上', unit: '第二单元', lessonName: '师说', knowledgePoints: ['论证方法', '"师道"内涵', '对比结构'] },
    ],
  },

  // === 小学段文言文（扩展） ===
  {
    id: 'text-013',
    title: '杨氏之子',
    author: '刘义庆',
    dynasty: '南朝',
    cadalId: 'CADAL-2024013',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=杨氏之子·古籍原图',
    gradeLevel: [5],
    schoolStage: ['primary'],
    tags: ['文言文', '世说新语', '童趣', '机智'],
    difficulty: 3,
    textbookMatch: [
      { grade: 5, semester: '下', unit: '第八单元', lessonName: '杨氏之子', knowledgePoints: ['文言实词', '对话描写', '魏晋风度', '巧妙应对'] },
    ],
  },
  {
    id: 'text-014',
    title: '自相矛盾',
    author: '韩非',
    dynasty: '战国',
    cadalId: 'CADAL-2024014',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=自相矛盾·古籍原图',
    gradeLevel: [5],
    schoolStage: ['primary'],
    tags: ['文言文', '寓言', '韩非子', '逻辑'],
    difficulty: 3,
    textbookMatch: [
      { grade: 5, semester: '下', unit: '第六单元', lessonName: '自相矛盾', knowledgePoints: ['文言实词', '寓言寓意', '逻辑思辨', '成语来源'] },
    ],
  },
  {
    id: 'text-015',
    title: '田忌赛马',
    author: '司马迁',
    dynasty: '汉',
    cadalId: 'CADAL-2024015',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=田忌赛马·古籍原图',
    gradeLevel: [5],
    schoolStage: ['primary'],
    tags: ['文言文', '史记', '智慧', '谋略'],
    difficulty: 3,
    textbookMatch: [
      { grade: 5, semester: '下', unit: '第六单元', lessonName: '田忌赛马', knowledgePoints: ['文言实词', '叙事顺序', '谋略智慧', '人物对话'] },
    ],
  },
  {
    id: 'text-016',
    title: '伯牙鼓琴',
    author: '吕不韦',
    dynasty: '战国',
    cadalId: 'CADAL-2024016',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=伯牙鼓琴·古籍原图',
    gradeLevel: [6],
    schoolStage: ['primary'],
    tags: ['文言文', '吕氏春秋', '知音', '友情'],
    difficulty: 3,
    textbookMatch: [
      { grade: 6, semester: '上', unit: '第七单元', lessonName: '伯牙鼓琴', knowledgePoints: ['文言实词', '知音主题', '比喻描写', '情感表达'] },
    ],
  },
  {
    id: 'text-017',
    title: '书戴嵩画牛',
    author: '苏轼',
    dynasty: '宋',
    cadalId: 'CADAL-2024017',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=书戴嵩画牛·古籍原图',
    gradeLevel: [6],
    schoolStage: ['primary'],
    tags: ['文言文', '题跋', '艺术', '求实'],
    difficulty: 3,
    textbookMatch: [
      { grade: 6, semester: '上', unit: '第七单元', lessonName: '书戴嵩画牛', knowledgePoints: ['文言实词', '题跋文体', '观察求实', '词类活用'] },
    ],
  },
  {
    id: 'text-018',
    title: '学弈',
    author: '孟子',
    dynasty: '战国',
    cadalId: 'CADAL-2024018',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=学弈·古籍原图',
    gradeLevel: [6],
    schoolStage: ['primary'],
    tags: ['文言文', '孟子', '学习', '专心'],
    difficulty: 3,
    textbookMatch: [
      { grade: 6, semester: '下', unit: '第五单元', lessonName: '学弈', knowledgePoints: ['文言实词', '专心致志', '对比写法', '成语出处'] },
    ],
  },
  {
    id: 'text-019',
    title: '两小儿辩日',
    author: '列子',
    dynasty: '战国',
    cadalId: 'CADAL-2024019',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=两小儿辩日·古籍原图',
    gradeLevel: [6],
    schoolStage: ['primary'],
    tags: ['文言文', '列子', '辩论', '求知'],
    difficulty: 3,
    textbookMatch: [
      { grade: 6, semester: '下', unit: '第五单元', lessonName: '两小儿辩日', knowledgePoints: ['文言实词', '古今异义', '论辩结构', '求知精神'] },
    ],
  },
  {
    id: 'text-020',
    title: '囊萤夜读',
    author: '佚名',
    dynasty: '唐',
    cadalId: 'CADAL-2024020',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=囊萤夜读·古籍原图',
    gradeLevel: [4],
    schoolStage: ['primary'],
    tags: ['文言文', '勤学', '成语', '刻苦'],
    difficulty: 2,
    textbookMatch: [
      { grade: 4, semester: '下', unit: '第七单元', lessonName: '囊萤夜读', knowledgePoints: ['文言实词', '勤学主题', '成语来源', '简练叙事'] },
    ],
  },
  {
    id: 'text-021',
    title: '铁杵成针',
    author: '佚名',
    dynasty: '宋',
    cadalId: 'CADAL-2024021',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=铁杵成针·古籍原图',
    gradeLevel: [4],
    schoolStage: ['primary'],
    tags: ['文言文', '勤学', '李白', '毅力'],
    difficulty: 2,
    textbookMatch: [
      { grade: 4, semester: '下', unit: '第七单元', lessonName: '铁杵成针', knowledgePoints: ['文言实词', '勤学主题', '成语来源', '人物描写'] },
    ],
  },
  {
    id: 'text-022',
    title: '古人谈读书（一）',
    author: '孔子',
    dynasty: '春秋',
    cadalId: 'CADAL-2024022',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=古人谈读书·古籍原图',
    gradeLevel: [5],
    schoolStage: ['primary'],
    tags: ['文言文', '论语', '读书', '学习'],
    difficulty: 3,
    textbookMatch: [
      { grade: 5, semester: '上', unit: '第八单元', lessonName: '古人谈读书（一）', knowledgePoints: ['文言实词', '论语名句', '学习态度', '通假字'] },
    ],
  },
  {
    id: 'text-023',
    title: '古人谈读书（二）',
    author: '朱熹',
    dynasty: '宋',
    cadalId: 'CADAL-2024023',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=古人谈读书·古籍原图',
    gradeLevel: [5],
    schoolStage: ['primary'],
    tags: ['文言文', '朱子', '读书', '方法'],
    difficulty: 3,
    textbookMatch: [
      { grade: 5, semester: '上', unit: '第八单元', lessonName: '古人谈读书（二）', knowledgePoints: ['文言实词', '读书方法', '古今异义', '说理结构'] },
    ],
  },
  {
    id: 'text-024',
    title: '古人谈读书（三）',
    author: '曾国藩',
    dynasty: '清',
    cadalId: 'CADAL-2024024',
    cadalImageUrl: 'https://placehold.co/400x600/f5e6d3/8b4513?text=古人谈读书·古籍原图',
    gradeLevel: [5],
    schoolStage: ['primary'],
    tags: ['文言文', '家书', '读书', '立志'],
    difficulty: 3,
    textbookMatch: [
      { grade: 5, semester: '上', unit: '第八单元', lessonName: '古人谈读书（三）', knowledgePoints: ['文言实词', '读书三要', '立志恒心', '虚词用法'] },
    ],
  },
];

// ---- 三层文本内容 ----
export const mockTieredContent: Record<string, TieredContent> = {
  'text-001': {
    original: '牀前明月光，疑是地上霜。舉頭望明月，低頭思故鄉。',
    adapted: '床前明月光，疑是地上霜。举头望明月，低头思故乡。',
    vernacular: '【白话解读】皎洁的月光洒在床前，好像地上铺了一层白霜。抬头望着天上的明月，不禁低下头思念起远方的家乡。考点：比喻（月光比作霜）、对仗（举头-低头、望-思）。',
    stageLevel: 'primary',
  },
  'text-002': {
    original: '人之初，性本善。性相近，習相遠。苟不教，性乃遷。',
    adapted: '人之初，性本善。性相近，习相远。苟不教，性乃迁。',
    vernacular: '【白话解读】人刚出生时本性善良，天性都差不多，但后天环境不同习惯就会差很远。考点："初"（刚、开始）、"迁"（改变）、对比论证。',
    stageLevel: 'primary',
  },
  'text-003': {
    original: '宋人有耕者。田中有株，兔走觸株，折頸而死。因釋其耒而守株，冀復得兔。',
    adapted: '宋人有耕者。田中有株，兔走触株，折颈而死。因释其耒而守株，冀复得兔。',
    vernacular: '【白话解读】宋国农夫田里有个树桩，兔子撞上去死了。农夫放下农具守在树桩旁等下一只。考点："走"（跑，古今异义）、"释"（放下）、"冀"（希望）。寓意：不能死守经验、心存侥幸。',
    stageLevel: 'primary',
  },
  'text-004': {
    original: '半畝方塘一鑑開，天光雲影共徘徊。問渠那得清如許，爲有源頭活水來。',
    adapted: '半亩方塘一鉴开，天光云影共徘徊。问渠那得清如许，为有源头活水来。',
    vernacular: '【白话解读】池塘像镜子，天光云影在水面移动。为什么这么清澈？因为有活水源源不断流来。比喻读书学习——不断学习新知识，思想才能保持清晰。考点：比喻（池塘喻心智、活水喻新知）、设问修辞。',
    stageLevel: 'primary',
  },
  'text-006': {
    original: '日照香爐生紫煙，遙看瀑布掛前川。飛流直下三千尺，疑是銀河落九天。',
    adapted: '日照香炉生紫烟，遥看瀑布挂前川。飞流直下三千尺，疑是银河落九天。',
    vernacular: '【白话解读】阳光照香炉峰升起紫烟，瀑布像白练挂在山前。三千尺飞泻而下，怀疑是银河从天上落下来。考点：夸张（三千尺）、比喻（银河）、视觉描写。',
    stageLevel: 'primary',
  },
  'text-007': {
    original: '慶曆四年春，滕子京謫守巴陵郡。越明年，政通人和，百廢具興，乃重修岳陽樓，增其舊制，刻唐賢今人詩賦於其上，屬予作文以記之。\n\n予觀夫巴陵勝狀，在洞庭一湖。銜遠山，吞長江，浩浩湯湯，橫無際涯，朝暉夕陰，氣象萬千，此則岳陽樓之大觀也，前人之述備矣。然則北通巫峽，南極瀟湘，遷客騷人，多會於此，覽物之情，得無異乎？\n\n若夫霪雨霏霏，連月不開，陰風怒號，濁浪排空，日星隱曜，山岳潛形，商旅不行，檣傾楫摧，薄暮冥冥，虎嘯猿啼。登斯樓也，則有去國懷鄉，憂讒畏譏，滿目蕭然，感極而悲者矣。\n\n至若春和景明，波瀾不驚，上下天光，一碧萬頃，沙鷗翔集，錦鱗游泳，岸芷汀蘭，鬱鬱青青。而或長煙一空，皓月千里，浮光躍金，靜影沉璧，漁歌互答，此樂何極！登斯樓也，則有心曠神怡，寵辱偕忘，把酒臨風，其喜洋洋者矣。\n\n嗟夫！予嘗求古仁人之心，或異二者之為，何哉？不以物喜，不以己悲，居廟堂之高則憂其民，處江湖之遠則憂其君。是進亦憂，退亦憂。然則何時而樂耶？其必曰"先天下之憂而憂，後天下之樂而樂"乎！噫！微斯人，吾誰與歸？',
    adapted: '庆历四年春，滕子京谪守巴陵郡。越明年，政通人和，百废具兴，乃重修岳阳楼，增其旧制，刻唐贤今人诗赋于其上，属予作文以记之。\n\n予观夫巴陵胜状，在洞庭一湖。衔远山，吞长江，浩浩汤汤，横无际涯，朝晖夕阴，气象万千，此则岳阳楼之大观也，前人之述备矣。然则北通巫峡，南极潇湘，迁客骚人，多会于此，览物之情，得无异乎？\n\n若夫霪雨霏霏，连月不开，阴风怒号，浊浪排空，日星隐曜，山岳潜形，商旅不行，樯倾楫摧，薄暮冥冥，虎啸猿啼。登斯楼也，则有去国怀乡，忧谗畏讥，满目萧然，感极而悲者矣。\n\n至若春和景明，波澜不惊，上下天光，一碧万顷，沙鸥翔集，锦鳞游泳，岸芷汀兰，郁郁青青。而或长烟一空，皓月千里，浮光跃金，静影沉璧，渔歌互答，此乐何极！登斯楼也，则有心旷神怡，宠辱偕忘，把酒临风，其喜洋洋者矣。\n\n嗟夫！予尝求古仁人之心，或异二者之为，何哉？不以物喜，不以己悲，居庙堂之高则忧其民，处江湖之远则忧其君。是进亦忧，退亦忧。然则何时而乐耶？其必曰"先天下之忧而忧，后天下之乐而乐"乎！噫！微斯人，吾谁与归？',
    vernacular: '【白话解读】庆历四年春天，滕子京被贬到巴陵郡做太守。过了一年，政事顺利，百姓和乐，于是重新修建岳阳楼。我观赏巴陵的美景，全在洞庭湖上——它衔着远山、吞没长江，水势浩大、无边无际。\n\n阴雨连绵时，狂风怒号、浊浪滔天，登上此楼就会产生离开国都、怀念家乡的悲凉之感。而春天和暖时，波澜不惊、碧波万顷，沙鸥飞翔、鱼儿游动，登上此楼则心胸开阔、宠辱皆忘。\n\n最后范仲淹发出千古名句："不以物喜，不以己悲""先天下之忧而忧，后天下之乐而乐"。考点："具"通"俱"（通假字）、"属"通"嘱"（通假字）、"以"的用法（介词/连词）、景物描写与情感变化的关系、名句默写。',
    stageLevel: 'junior',
  },
  'text-008': {
    original: '臣亮言：先帝創業未半而中道崩殂，今天下三分，益州疲弊，此誠危急存亡之秋也。然侍衛之臣不懈於內，忠志之士忘身於外者，蓋追先帝之殊遇，欲報之於陛下也。誠宜開張聖聽，以光先帝遺德，恢弘志士之氣，不宜妄自菲薄，引喻失義，以塞忠諫之路也。\n\n宮中府中，俱爲一體，陟罰臧否，不宜異同。若有作奸犯科及爲忠善者，宜付有司論其刑賞，以昭陛下平明之理，不宜偏私，使內外異法也。\n\n親賢臣，遠小人，此先漢所以興隆也；親小人，遠賢臣，此後漢所以傾頹也。先帝在時，每與臣論此事，未嘗不歎息痛恨於桓、靈也。\n\n臣本布衣，躬耕於南陽，苟全性命於亂世，不求聞達於諸侯。先帝不以臣卑鄙，猥自枉屈，三顧臣於草廬之中，諮臣以當世之事，由是感激，遂許先帝以驅馳。後值傾覆，受任於敗軍之際，奉命於危難之間，爾來二十有一年矣。\n\n先帝知臣謹慎，故臨崩寄臣以大事也。受命以來，夙夜憂歎，恐託付不效，以傷先帝之明，故五月渡瀘，深入不毛。今南方已定，兵甲已足，當獎率三軍，北定中原，庶竭駑鈍，攘除姦凶，興復漢室，還於舊都。此臣所以報先帝而忠陛下之職分也。\n\n願陛下託臣以討賊興復之效，不效，則治臣之罪，以告先帝之靈。若無興德之言，則責攸之、禕、允等之慢，以彰其咎。陛下亦宜自謀，以諮諏善道，察納雅言，深追先帝遺詔。臣不勝受恩感激。\n\n今當遠離，臨表涕零，不知所言。',
    adapted: '臣亮言：先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也。然侍卫之臣不懈于内，忠志之士忘身于外者，盖追先帝之殊遇，欲报之于陛下也。诚宜开张圣听，以光先帝遗德，恢弘志士之气，不宜妄自菲薄，引喻失义，以塞忠谏之路也。\n\n宫中府中，俱为一体，陟罚臧否，不宜异同。若有作奸犯科及为忠善者，宜付有司论其刑赏，以昭陛下平明之理，不宜偏私，使内外异法也。\n\n亲贤臣，远小人，此先汉所以兴隆也；亲小人，远贤臣，此后汉所以倾颓也。先帝在时，每与臣论此事，未尝不叹息痛恨于桓、灵也。\n\n臣本布衣，躬耕于南阳，苟全性命于乱世，不求闻达于诸侯。先帝不以臣卑鄙，猥自枉屈，三顾臣于草庐之中，咨臣以当世之事，由是感激，遂许先帝以驱驰。后值倾覆，受任于败军之际，奉命于危难之间，尔来二十有一年矣。\n\n先帝知臣谨慎，故临崩寄臣以大事也。受命以来，夙夜忧叹，恐托付不效，以伤先帝之明，故五月渡泸，深入不毛。今南方已定，兵甲已足，当奖率三军，北定中原，庶竭驽钝，攘除奸凶，兴复汉室，还于旧都。此臣所以报先帝而忠陛下之职分也。\n\n愿陛下托臣以讨贼兴复之效，不效，则治臣之罪，以告先帝之灵。陛下亦宜自谋，以咨诹善道，察纳雅言，深追先帝遗诏。臣不胜受恩感激。今当远离，临表涕零，不知所言。',
    vernacular: '【白话解读】这是诸葛亮北伐前写给后主刘禅的奏表，是中国文学史上最著名的表文之一。全文情真意切，既分析了天下形势、提出了治国建议（开张圣听、赏罚分明、亲贤远佞），又回顾了自己的身世和与先帝刘备的知遇之恩，最后表达北伐中原、兴复汉室的决心。考点："崩殂"（帝王去世）、"秋"（时候，古今异义）、"卑鄙"（身份低微，古今异义）、"感激"（感动奋发，古今异义）、"所以"（用来……的）、三顾茅庐典故、名句默写。',
    stageLevel: 'junior',
  },
  'text-009': {
    original: '晉太元中，武陵人捕魚爲業。緣溪行，忘路之遠近。忽逢桃花林，夾岸數百步，中無雜樹，芳草鮮美，落英繽紛。漁人甚異之，復前行，欲窮其林。\n\n林盡水源，便得一山，山有小口，仿佛若有光。便捨船，從口入。初極狹，才通人。復行數十步，豁然開朗。土地平曠，屋舍儼然，有良田、美池、桑竹之屬。阡陌交通，雞犬相聞。其中往來種作，男女衣著，悉如外人。黃髮垂髫，並怡然自樂。\n\n見漁人，乃大驚，問所從來。具答之。便要還家，設酒殺雞作食。村中聞有此人，咸來問訊。自云先世避秦時亂，率妻子邑人來此絕境，不復出焉，遂與外人間隔。問今是何世，乃不知有漢，無論魏晉。此人一一爲具言所聞，皆歎惋。餘人各復延至其家，皆出酒食。停數日，辭去。此中人語云："不足爲外人道也。"\n\n既出，得其船，便扶向路，處處誌之。及郡下，詣太守，說如此。太守即遣人隨其往，尋向所誌，遂迷，不復得路。\n\n南陽劉子驥，高尚士也，聞之，欣然規往。未果，尋病終。後遂無問津者。',
    adapted: '晋太元中，武陵人捕鱼为业。缘溪行，忘路之远近。忽逢桃花林，夹岸数百步，中无杂树，芳草鲜美，落英缤纷。渔人甚异之，复前行，欲穷其林。\n\n林尽水源，便得一山，山有小口，仿佛若有光。便舍船，从口入。初极狭，才通人。复行数十步，豁然开朗。土地平旷，屋舍俨然，有良田、美池、桑竹之属。阡陌交通，鸡犬相闻。其中往来种作，男女衣着，悉如外人。黄发垂髫，并怡然自乐。\n\n见渔人，乃大惊，问所从来。具答之。便要还家，设酒杀鸡作食。村中闻有此人，咸来问讯。自云先世避秦时乱，率妻子邑人来此绝境，不复出焉，遂与外人间隔。问今是何世，乃不知有汉，无论魏晋。此人一一为具言所闻，皆叹惋。余人各复延至其家，皆出酒食。停数日，辞去。此中人语云："不足为外人道也。"\n\n既出，得其船，便扶向路，处处志之。及郡下，诣太守，说如此。太守即遣人随其往，寻向所志，遂迷，不复得路。\n\n南阳刘子骥，高尚士也，闻之，欣然规往。未果，寻病终。后遂无问津者。',
    vernacular: '【白话解读】东晋太元年间，武陵渔人偶然发现桃花源——一个与世隔绝的理想世界。这里土地平坦、屋舍整齐，人们过着安宁和乐的生活，完全不知外面已经历了汉、魏、晋的朝代更迭。渔人离开后做了标记，但再也找不到回去的路。陶渊明借这个故事表达了对和平安宁生活的向往。考点："缘"（沿着）、"要"通"邀"（通假字）、"志"（做标记）、"寻"（不久）、"问津"（探求）、叙事顺序、环境描写、成语"世外桃源""豁然开朗""无人问津"的来源。',
    stageLevel: 'junior',
  },
  'text-010': {
    original: '壬戌之秋，七月既望，蘇子與客泛舟遊於赤壁之下。清風徐來，水波不興。舉酒屬客，誦明月之詩，歌窈窕之章。少焉，月出於東山之上，徘徊於斗牛之間。白露橫江，水光接天。縱一葦之所如，凌萬頃之茫然。浩浩乎如馮虛御風，而不知其所止；飄飄乎如遺世獨立，羽化而登仙。\n\n於是飲酒樂甚，扣舷而歌之。歌曰："桂棹兮蘭槳，擊空明兮泝流光。渺渺兮予懷，望美人兮天一方。"客有吹洞簫者，倚歌而和之。其聲嗚嗚然，如怨如慕，如泣如訴，餘音嫋嫋，不絕如縷。舞幽壑之潛蛟，泣孤舟之嫠婦。\n\n蘇子愀然，正襟危坐而問客曰："何爲其然也？"客曰："月明星稀，烏鵲南飛，此非曹孟德之詩乎？西望夏口，東望武昌，山川相繆，鬱乎蒼蒼，此非孟德之困於周郎者乎？方其破荊州，下江陵，順流而東也，舳艫千里，旌旗蔽空，釃酒臨江，橫槊賦詩，固一世之雄也，而今安在哉？"\n\n蘇子曰："客亦知夫水與月乎？逝者如斯，而未嘗往也；盈虛者如彼，而卒莫消長也。蓋將自其變者而觀之，則天地曾不能以一瞬；自其不變者而觀之，則物與我皆無盡也，而又何羨乎！"\n\n客喜而笑，洗盞更酌。肴核既盡，杯盤狼藉。相與枕藉乎舟中，不知東方之既白。',
    adapted: '壬戌之秋，七月既望，苏子与客泛舟游于赤壁之下。清风徐来，水波不兴。举酒属客，诵明月之诗，歌窈窕之章。少焉，月出于东山之上，徘徊于斗牛之间。白露横江，水光接天。纵一苇之所如，凌万顷之茫然。浩浩乎如冯虚御风，而不知其所止；飘飘乎如遗世独立，羽化而登仙。\n\n于是饮酒乐甚，扣舷而歌之。歌曰："桂棹兮兰桨，击空明兮溯流光。渺渺兮予怀，望美人兮天一方。"客有吹洞箫者，倚歌而和之。其声呜呜然，如怨如慕，如泣如诉，余音袅袅，不绝如缕。舞幽壑之潜蛟，泣孤舟之嫠妇。\n\n苏子愀然，正襟危坐而问客曰："何为其然也？"客曰："月明星稀，乌鹊南飞，此非曹孟德之诗乎？西望夏口，东望武昌，山川相缪，郁乎苍苍，此非孟德之困于周郎者乎？方其破荆州，下江陵，顺流而东也，舳舻千里，旌旗蔽空，酾酒临江，横槊赋诗，固一世之雄也，而今安在哉？"\n\n苏子曰："客亦知夫水与月乎？逝者如斯，而未尝往也；盈虚者如彼，而卒莫消长也。盖将自其变者而观之，则天地曾不能以一瞬；自其不变者而观之，则物与我皆无尽也，而又何羡乎！"\n\n客喜而笑，洗盏更酌。肴核既尽，杯盘狼藉。相与枕藉乎舟中，不知东方之既白。',
    vernacular: '【白话解读】壬戌年七月十六，苏轼与客人泛舟赤壁之下，饮酒赏月、扣舷而歌。客人吹箫声悲凉，引发了对曹操等历史英雄"而今安在"的感慨。苏轼以水和月为喻，阐述了"变与不变"的哲理——从变化的角度看，天地万物瞬息万变；从不变的角度看，万物与我都无穷无尽。全文将景物、哲理、情感融为一体，是赋体散文的巅峰之作。考点："既望"（农历十六）、"属"通"嘱"（通假字）、"于"的介词用法、主客问答结构、变与不变的哲理、"遗世独立""羽化登仙""沧海一粟"等成语���处、名句默写。',
    stageLevel: 'senior',
  },
  'text-011': {
    original: '君子曰：學不可以已。青，取之於藍而青於藍；冰，水爲之而寒於水。木直中繩，輮以爲輪，其曲中規，雖有槁暴，不復挺者，輮使之然也。故木受繩則直，金就礪則利，君子博學而日參省乎己，則知明而行無過矣。\n\n吾嘗終日而思矣，不如須臾之所學也；吾嘗跂而望矣，不如登高之博見也。登高而招，臂非加長也，而見者遠；順風而呼，聲非加疾也，而聞者彰。假輿馬者，非利足也，而致千里；假舟楫者，非能水也，而絕江河。君子生非異也，善假於物也。\n\n積土成山，風雨興焉；積水成淵，蛟龍生焉；積善成德，而神明自得，聖心備焉。故不積跬步，無以至千里；不積小流，無以成江海。騏驥一躍，不能十步；駑馬十駕，功在不捨。鍥而舍之，朽木不折；鍥而不捨，金石可鏤。',
    adapted: '君子曰：学不可以已。青，取之于蓝而青于蓝；冰，水为之而寒于水。木直中绳，輮以为轮，其曲中规，虽有槁暴，不复挺者，輮使之然也。故木受绳则直，金就砺则利，君子博学而日参省乎己，则知明而行无过矣。\n\n吾尝终日而思矣，不如须臾之所学也；吾尝跂而望矣，不如登高之博见也。登高而招，臂非加长也，而见者远；顺风而呼，声非加疾也，而闻者彰。假舆马者，非利足也，而致千里；假舟楫者，非能水也，而绝江河。君子生非异也，善假于物也。\n\n积土成山，风雨兴焉；积水成渊，蛟龙生焉；积善成德，而神明自得，圣心备焉。故不积跬步，无以至千里；不积小流，无以成江海。骐骥一跃，不能十步；驽马十驾，功在不舍。锲而舍之，朽木不折；锲而不舍，金石可镂。',
    vernacular: '【白话解读】荀子开篇提出"学不可以已"的中心论点。用"青出于蓝""冰寒于水"比喻学习可以超越本源；用"登高而招""顺风而呼"说明善用外物的重要性；用"积土成山""积水成渊"论证积累的意义；用"骐骥一跃""驽马十驾"对比说明坚持不懈比天赋更重要。全文大量运用比喻论证和对比论证，是先秦论说文的典范。考点："已"（停止）、"于"（比，介词用法）、"輮"通"煣"、"生"通"性"（通假字）、"跬步"（半步）、比喻论证与对比论证的辨析、"青出于蓝""锲而不舍"等成语出处、名句默写。',
    stageLevel: 'senior',
  },
  'text-012': {
    original: '古之學者必有師。師者，所以傳道受業解惑也。人非生而知之者，孰能無惑？惑而不從師，其爲惑也，終不解矣。\n\n生乎吾前，其聞道也固先乎吾，吾從而師之；生乎吾後，其聞道也亦先乎吾，吾從而師之。吾師道也，夫庸知其年之先後生於吾乎？是故無貴無賤，無長無少，道之所存，師之所存也。\n\n嗟乎！師道之不傳也久矣！欲人之無惑也難矣！古之聖人，其出人也遠矣，猶且從師而問焉；今之眾人，其下聖人也亦遠矣，而恥學於師。是故聖益聖，愚益愚。聖人之所以爲聖，愚人之所以爲愚，其皆出於此乎？\n\n愛其子，擇師而教之；於其身也，則恥師焉，惑矣。彼童子之師，授之書而習其句讀者，非吾所謂傳其道解其惑者也。句讀之不知，惑之不解，或師焉，或不焉，小學而大遺，吾未見其明也。\n\n孔子曰：三人行，則必有我師。是故弟子不必不如師，師不必賢於弟子，聞道有先後，術業有專攻，如是而已。\n\n李氏子蟠，年十七，好古文，六藝經傳皆通習之，不拘於時，學於余。余嘉其能行古道，作《師說》以貽之。',
    adapted: '古之学者必有师。师者，所以传道受业解惑也。人非生而知之者，孰能无惑？惑而不从师，其为惑也，终不解矣。\n\n生乎吾前，其闻道也固先乎吾，吾从而师之；生乎吾后，其闻道也亦先乎吾，吾从而师之。吾师道也，夫庸知其年之先后生于吾乎？是故无贵无贱，无长无少，道之所存，师之所存也。\n\n嗟乎！师道之不传也久矣！欲人之无惑也难矣！古之圣人，其出人也远矣，犹且从师而问焉；今之众人，其下圣人也亦远矣，而耻学于师。是故圣益圣，愚益愚。\n\n爱其子，择师而教之；于其身也，则耻师焉，惑矣。彼童子之师，授之书而习其句读者，非吾所谓传其道解其惑者也。句读之不知，惑之不解，或师焉，或不焉，小学而大遗，吾未见其明也。\n\n孔子曰：三人行，则必有我师。是故弟子不必不如师，师不必贤于弟子，闻道有先后，术业有专攻，如是而已。\n\n李氏子蟠，年十七，好古文，六艺经传皆通习之，不拘于时，学于余。余嘉其能行古道，作《师说》以贻之。',
    vernacular: '【白话解读】韩愈针对当时"耻学于师"的不良风气，提出"古之学者必有师"的核心观点。文章层层论证：首先说明从师的必要性（解惑），其次提出择师标准（道之所存，师之所存），再通过古今对比批评耻师风气，最后以孔子"三人行必有我师"和"弟子不必不如师"收束，并说明写作缘由。考点："受"通"授"（通假字）、"所以"（用来……的，古今异义）、"从而"（跟从并且，古今异义）、"师"的名词与动词用法、"之"的多种用法、对比论证、"三人行必有我师""闻道有先后，术业有专攻"名句默写。',
    stageLevel: 'senior',
  },
  'text-013': {
    original: '梁國楊氏子九歲，甚聰惠。孔君平詣其父，父不在，乃呼兒出。為設果，果有楊梅。孔指以示兒曰：「此是君家果。」兒應聲答曰：「未聞孔雀是夫子家禽。」',
    adapted: '梁国杨氏子九岁，甚聪惠。孔君平诣其父，父不在，乃呼儿出。为设果，果有杨梅。孔指以示儿曰："此是君家果。"儿应声答曰："未闻孔雀是夫子家禽。"',
    vernacular: '【白话解读】梁国一户姓杨人家的孩子才九岁，非常聪明。孔君平来拜访他的父亲，父亲不在，于是把孩子叫出来。孩子给孔君平摆上水果，其中有杨梅。孔君平指着杨梅对孩子说："这是你家的水果。"孩子马上回答："我可没听说过孔雀是先生家的鸟。"考点："惠"通"慧"（通假字）、"诣"（拜访）、"乃"（于是）、"以示"（给……看）、"夫子"（对长辈的尊称）、语言机智的描写。',
    stageLevel: 'primary',
  },
  'text-014': {
    original: '楚人有鬻盾與矛者。譽之曰：「吾盾之堅，物莫能陷也。」又譽其矛曰：「吾矛之利，於物無不陷也。」或曰：「以子之矛，陷子之盾，何如？」其人弗能應也。',
    adapted: '楚人有鬻盾与矛者。誉之曰："吾盾之坚，物莫能陷也。"又誉其矛曰："吾矛之利，于物无不陷也。"或曰："以子之矛，陷子之盾，何如？"其人弗能应也。',
    vernacular: '【白话解读】楚国有一个卖盾和矛的人，他夸自己的盾说："我的盾很坚固，没有什么东西能刺穿它。"又夸自己的矛说："我的矛很锋利，没有什么东西刺不穿。"有人问他："用你的矛刺你的盾，会怎么样？"那个人就回答不上来了。考点："鬻"（卖）、"誉"（夸耀）、"陷"（刺穿）、"或"（有人，古今异义）、"弗"（不）、逻辑矛盾与寓意。',
    stageLevel: 'primary',
  },
  'text-015': {
    original: '忌數與齊諸公子馳逐重射。孫子見其馬足不甚相遠，馬有上、中、下輩。於是孫子謂田忌曰：「君弟重射，臣能令君勝。」田忌信然之。',
    adapted: '忌数与齐诸公子驰逐重射。孙子见其马足不甚相远，马有上、中、下辈。于是孙子谓田忌曰："君弟重射，臣能令君胜。"田忌信然之。',
    vernacular: '【白话解读】田忌多次和齐国的公子们赛马，下了很大的赌注。孙膑看到田忌的马和对手的马脚力相差不大，马分上、中、下三个等级。于是孙膑对田忌说："您只管下大赌注，我能让您取胜。"田忌相信并听从了他。考点："数"（屡次）、"诸"（各位）、"驰逐"（赛马）、"弟"通"第"（只管）、"然"（认为……对，意动用法）、叙事顺序与谋略。',
    stageLevel: 'primary',
  },
  'text-016': {
    original: '伯牙鼓琴，鍾子期聽之。方鼓琴而志在太山。鍾子期曰：「善哉乎鼓琴，巍巍乎若太山！」少選之間，而志在流水。鍾子期又曰：「善哉乎鼓琴，湯湯乎若流水！」鍾子期死，伯牙破琴絕弦，終身不復鼓琴，以為世無足復為鼓琴者。',
    adapted: '伯牙鼓琴，锺子期听之。方鼓琴而志在太山。锺子期曰："善哉乎鼓琴，巍巍乎若太山！"少选之间，而志在流水。锺子期又曰："善哉乎鼓琴，汤汤乎若流水！"锺子期死，伯牙破琴绝弦，终身不复鼓琴，以为世无足复为鼓琴者。',
    vernacular: '【白话解读】伯牙弹琴，锺子期听他弹奏。伯牙心里想着泰山，锺子期就说："弹得好啊，高峻得像泰山！"过了一会儿伯牙想到流水，锺子期又说："弹得好啊，浩荡得像流水！"锺子期死后，伯牙摔破琴、弄断弦，终身不再弹琴，认为世上再没有值得为之弹琴的人了。考点："鼓"（弹奏）、"方"（正在）、"善哉"（真好啊）、"汤汤"（水势浩大）、"绝"（弄断）、"知音"主题。',
    stageLevel: 'primary',
  },
  'text-017': {
    original: '蜀中有杜處士，好書畫，所寶以百數。有戴嵩《牛》一軸，尤所愛，錦囊玉軸，常以自隨。一日曝書畫，有一牧童見之，拊掌大笑。曰：「此畫鬥牛也。牛鬥，力在角，尾搐入兩股間。今乃掉尾而鬥，謬矣！」處士笑而然之。',
    adapted: '蜀中有杜处士，好书画，所宝以百数。有戴嵩《牛》一轴，尤所爱，锦囊玉轴，常以自随。一日曝书画，有一牧童见之，拊掌大笑。曰："此画斗牛也。牛斗，力在角，尾搐入两股间。今乃掉尾而斗，谬矣！"处士笑而然之。',
    vernacular: '【白话解读】四川有个杜处士，喜爱书画，珍藏的作品数以百计。其中一幅戴嵩画的《牛》他尤其珍爱，用锦缎做囊、玉石做轴，常带在身边。一天晒画时，一个牧童看到后拍手大笑，说："这画的是斗牛。牛相斗时力气在角上，尾巴夹在两条大腿之间，现在却甩着尾巴相斗，画错了！"杜处士笑着认为他说得对。考点："处士"（隐居的读书人）、"宝"（珍藏，词类活用）、"曝"（晒）、"搐"（夹紧）、"股"（大腿，古今异义）、"掉"（摆动，古今异义）、实事求是。',
    stageLevel: 'primary',
  },
  'text-018': {
    original: '弈秋，通國之善弈者也。使弈秋誨二人弈。其一人專心致志，惟弈秋之為聽。一人雖聽之，一心以為有鴻鵠將至，思援弓繳而射之。雖與之俱學，弗若之矣。為是其智弗若與？曰：非然也。',
    adapted: '弈秋，通国之善弈者也。使弈秋诲二人弈。其一人专心致志，惟弈秋之为听。一人虽听之，一心以为有鸿鹄将至，思援弓缴而射之。虽与之俱学，弗若之矣。为是其智弗若与？曰：非然也。',
    vernacular: '【白话解读】弈秋是全国最擅长下棋的人。让他教两个人下棋，其中一人专心致志，只听弈秋的教导；另一人虽然也在听，心里却想着天鹅要飞来，想去拉弓射它。虽然两人一起学习，后一个却不如前一个。是因为他的智力不如吗？回答说：不是这样的。考点："弈"（下棋）、"诲"（教导）、"鸿鹄"（天鹅）、"援"（拉引）、"弗若"（不如）、"专心致志"成语出处、专心的重要性。',
    stageLevel: 'primary',
  },
  'text-019': {
    original: '孔子東游，見兩小兒辯鬥，問其故。一兒曰：「我以日始出時去人近，而日中時遠也。」一兒以日初出遠，而日中時近也。一兒曰：「日初出大如車蓋，及日中則如盤盂，此不為遠者小而近者大乎？」一兒曰：「日初出滄滄涼涼，及其日中如探湯，此不為近者熱而遠者涼乎？」孔子不能決也。兩小兒笑曰：「孰為汝多知乎？」',
    adapted: '孔子东游，见两小儿辩斗，问其故。一儿曰："我以日始出时去人近，而日中时远也。"一儿以日初出远，而日中时近也。一儿曰："日初出大如车盖，及日中则如盘盂，此不为远者小而近者大乎？"一儿曰："日初出沧沧凉凉，及其日中如探汤，此不为近者热而远者凉乎？"孔子不能决也。两小儿笑曰："孰为汝多知乎？"',
    vernacular: '【白话解读】孔子到东方游历，看见两个小孩在争论，就问原因。一个说太阳刚出来时离人近、正午时远；另一个说刚出来时远、正午时近。一个用大小作比（车盖与盘盂），一个用冷热作比（凉与热水）。孔子不能判断谁对。两个小孩笑问："谁说你知识渊博呢？"考点："去"（距离，古今异义）、"及"（到）、"汤"（热水，古今异义）、"决"（判断）、"知"通"智"（通假字）、论辩结构与求知精神。',
    stageLevel: 'primary',
  },
  'text-020': {
    original: '胤恭勤不倦，博學多通。家貧不常得油。夏月則練囊盛數十螢火以照書，以夜繼日焉。',
    adapted: '胤恭勤不倦，博学多通。家贫不常得油。夏月则练囊盛数十萤火以照书，以夜继日焉。',
    vernacular: '【白话解读】车胤恭敬勤勉不知疲倦，学问广博、通晓多种知识。家里贫穷，不能经常得到灯油。夏天他就用白绢做的袋子装几十只萤火虫来照明读书，夜以继日地刻苦学习。考点："恭勤"（恭敬勤勉）、"通"（通晓）、"练囊"（白绢袋）、"盛"（装）、"以夜继日"（成语来源）、勤学主题。',
    stageLevel: 'primary',
  },
  'text-021': {
    original: '磨針溪，在眉州象耳山下。世傳李太白讀書山中，未成，棄去。過是溪，逢老媪方磨鐵杵。問之，曰：「欲作針。」太白感其意，還卒業。',
    adapted: '磨针溪，在眉州象耳山下。世传李太白读书山中，未成，弃去。过是溪，逢老媪方磨铁杵。问之，曰："欲作针。"太白感其意，还卒业。',
    vernacular: '【白话解读】磨针溪在眉州象耳山下。世人传说李白在山中读书，没有完成学业就放弃离开了。路过这条溪水时，遇到一位老妇人正在磨铁棒。李白问她，老妇人说："想把它磨成针。"李白被她的意志感动，回去完成了学业。考点："世传"（传说）、"弃"（放弃）、"是"（这，古今异义）、"老媪"（老妇人）、"方"（正在）、"感"（被感动）、"卒业"（完成学业）、"铁杵成针"成语来源。',
    stageLevel: 'primary',
  },
  'text-022': {
    original: '知之為知之，不知為不知，是知也。敏而好學，不恥下問。默而識之，學而不厭，誨人不倦。吾嘗終日不食，終夜不寢，以思，無益，不如學也。',
    adapted: '知之为知之，不知为不知，是知也。敏而好学，不耻下问。默而识之，学而不厌，诲人不倦。吾尝终日不食，终夜不寝，以思，无益，不如学也。',
    vernacular: '【白话解读】知道就是知道，不知道就是不知道，这才是智慧。聪敏又爱好学习，不以向地位低的人请教为耻。默默地记住，学习不满足，教导别人不疲倦。我曾经整天不吃、整夜不睡地思考，却没有益处，不如去学习。考点：最后一个"知"通"智"（通假字）、"敏"（聪敏）、"好"（喜爱）、"耻"（以……为耻，意动用法）、"识"（记住）、"厌"（满足，古今异义）、论语名句。',
    stageLevel: 'primary',
  },
  'text-023': {
    original: '余嘗謂：讀書有三到，謂心到、眼到、口到。心不在此，則眼不看仔細，心眼既不專一，卻只漫浪誦讀，決不能記，記亦不能久也。三到之中，心到最急。心既到矣，眼口豈不到乎？',
    adapted: '余尝谓：读书有三到，谓心到、眼到、口到。心不在此，则眼不看仔细，心眼既不专一，却只漫浪诵读，决不能记，记亦不能久也。三到之中，心到最急。心既到矣，眼口岂不到乎？',
    vernacular: '【白话解读】我曾经说：读书有三到，就是心到、眼到、口到。心不在这里，眼睛就不会仔细看；心和眼既然不专一，只是随便诵读，一定记不住，记住了也不能长久。三到之中，心到最为紧要。心既然到了，眼睛和嘴难道会不到吗？考点："余"（我）、"尝"（曾经）、"漫浪"（随便）、"决"（一定）、"急"（紧要，古今异义）、"岂"（难道）、读书方法说理。',
    stageLevel: 'primary',
  },
  'text-024': {
    original: '蓋士人讀書，第一要有志，第二要有識，第三要有恆。有志則斷不甘為下流。有識則知學問無盡，不敢以一得自足。有恆則斷無不成之事。此三者缺一不可。',
    adapted: '盖士人读书，第一要有志，第二要有识，第三要有恒。有志则断不甘为下流。有识则知学问无尽，不敢以一得自足。有恒则断无不成之事。此三者缺一不可。',
    vernacular: '【白话解读】读书人读书，第一要有志向，第二要有见识，第三要有恒心。有志向就绝不会甘心居于下流；有见识就知道学问没有尽头，不敢因一点收获就自我满足；有恒心就绝对没有做不成的事。这三者缺一不可。考点："盖"（发语词）、"士人"（读书人）、"识"（见识）、"恒"（恒心）、"断"（绝对）、"甘"（甘心）、"自足"（自我满足）、"读书三要"结构。',
    stageLevel: 'primary',
  },
  'text-025': {
    original: '春眠不覺曉，處處聞啼鳥。夜來風雨聲，花落知多少。',
    adapted: '春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。',
    vernacular: '【白话解读】春天睡觉不知不觉天就亮了，到处都能听到鸟儿的啼鸣。回想昨夜的风雨声，不知道吹落了多少花朵。考点：春日晨景、惜春之情、五言绝句。',
    stageLevel: 'primary',
  },
  'text-026': {
    original: '碧玉妝成一樹高，萬條垂下綠絲絛。不知細葉誰裁出，二月春風似剪刀。',
    adapted: '碧玉妆成一树高，万条垂下绿丝绦。不知细叶谁裁出，二月春风似剪刀。',
    vernacular: '【白话解读】高高的柳树像用碧玉打扮过，万千柳枝垂下来像绿色的丝带。不知道细嫩的柳叶是谁裁剪出来的，二月的春风就像一把灵巧的剪刀。考点：比喻（柳叶如剪刀）、咏物诗、七言绝句。',
    stageLevel: 'primary',
  },
  'text-027': {
    original: '小娃撐小艇，偷採白蓮回。不解藏蹤跡，浮萍一道開。',
    adapted: '小娃撑小艇，偷采白莲回。不解藏踪迹，浮萍一道开。',
    vernacular: '【白话解读】小孩儿撑着小船，偷偷采了白莲回来。他还不懂得隐藏自己的踪迹，水面的浮萍被小船划开了一道缝。考点：童趣、动作描写、五言绝句。',
    stageLevel: 'primary',
  },
  'text-028': {
    original: '泉眼無聲惜細流，樹陰照水愛晴柔。小荷才露尖尖角，早有蜻蜓立上頭。',
    adapted: '泉眼无声惜细流，树阴照水爱晴柔。小荷才露尖尖角，早有蜻蜓立上头。',
    vernacular: '【白话解读】泉眼悄悄流淌，舍不得细细的水流；树影映在水里，喜爱晴天柔和的风光。小小的荷叶才露出尖尖的嫩角，早有蜻蜓立在上头。考点：初夏小景、细腻观察、七言绝句。',
    stageLevel: 'primary',
  },
  'text-029': {
    original: '草長鶯飛二月天，拂堤楊柳醉春煙。兒童散學歸來早，忙趁東風放紙鳶。',
    adapted: '草长莺飞二月天，拂堤杨柳醉春烟。儿童散学归来早，忙趁东风放纸鸢。',
    vernacular: '【白话解读】青草生长、黄莺飞舞的二月天，杨柳拂着堤岸，沉醉在春天的雾气里。孩子们放学回来得早，赶忙趁着东风把风筝放上蓝天。考点：春日乡村、童趣、七言绝句。',
    stageLevel: 'primary',
  },
};

// ---- 备课教案 ----
export const mockLessonPlans: LessonPlan[] = [
  {
    id: 'plan-001',
    title: '《静夜思》古诗教学教案',
    targetGrade: 1,
    subject: '语文',
    textIds: ['text-001'],
    objectives: ['正确流利朗读古诗', '理解诗意，体会思乡之情', '认识"疑""霜""举"等生字'],
    teachingProcess: [
      { order: 1, title: '情境导入', duration: 5, content: '播放月亮图片，提问：看到月亮你会想到什么？引导学生自由发言', activities: ['图片展示', '自由讨论'] },
      { order: 2, title: '初读感知', duration: 8, content: '教师范读→学生跟读→指名读。使用简化适配版文本。', ancientTextRef: 'text-001', tier: 'adapted', activities: ['范读', '跟读', '指名读'] },
      { order: 3, title: '精读理解', duration: 12, content: '逐句讲解，结合白话解读版帮助理解。"疑是地上霜"——比喻手法。', ancientTextRef: 'text-001', tier: 'vernacular', activities: ['逐句讲解', '小组讨论', '比喻分析'] },
      { order: 4, title: '拓展延伸', duration: 8, content: '展示CADAL古籍原图，让学生感受古人书迹。提问：你还知道哪些写月亮的诗？', ancientTextRef: 'text-001', activities: ['原图欣赏', '知识迁移'] },
      { order: 5, title: '课堂总结', duration: 5, content: '回顾诗意和考点，布置课后练习', activities: ['总结', '布置作业'] },
    ],
    createdAt: '2025-03-10',
    authorId: 'teacher-001',
    isPublic: true,
    downloads: 156,
    tags: ['古诗教学', '一年级', '李白'],
  },
  {
    id: 'plan-002',
    title: '《岳阳楼记》精读教案——"先忧后乐"思想探究',
    targetGrade: 8,
    subject: '语文',
    textIds: ['text-007'],
    objectives: ['掌握文言虚词和重点实词', '分析景物描写与情感关系', '理解"先天下之忧而忧"的思想内涵'],
    teachingProcess: [
      { order: 1, title: '背景导入', duration: 8, content: '介绍范仲淹生平及"庆历新政"背景，播放岳阳楼图片', activities: ['背景介绍', '图片展示'] },
      { order: 2, title: '初读疏通', duration: 10, content: '学生借助简化版自读，标记疑难字词。教师讲解重点字词。', ancientTextRef: 'text-007', tier: 'adapted', activities: ['自主阅读', '字词讲解'] },
      { order: 3, title: '分段研读', duration: 15, content: '分组研读"迁客骚人"的两种览物之情，对比分析。使用原版文本体会骈散结合之美。', ancientTextRef: 'text-007', tier: 'original', activities: ['分组研读', '对比分析', '朗读体会'] },
      { order: 4, title: '主旨探究', duration: 10, content: '讨论"先天下之忧而忧，后天下之乐而乐"的现实意义。结合白话解读深化理解。', ancientTextRef: 'text-007', tier: 'vernacular', activities: ['小组讨论', '观点分享'] },
      { order: 5, title: '总结与练习', duration: 5, content: '课堂小测 + 布置背诵任务', activities: ['小测', '背诵'] },
    ],
    createdAt: '2025-03-12',
    authorId: 'teacher-001',
    isPublic: true,
    downloads: 89,
    tags: ['文言文教学', '八年级', '岳阳楼记'],
  },
  {
    id: 'plan-003',
    title: '《劝学》论证方法分析——高考文言文备考',
    targetGrade: 10,
    subject: '语文',
    textIds: ['text-011'],
    objectives: ['掌握比喻论证和对比论证', '积累高考高频文言虚词', '理解荀子学习观'],
    teachingProcess: [
      { order: 1, title: '导入', duration: 5, content: '提问："你为什么要学习？"引出荀子的学习观', activities: ['互动提问'] },
      { order: 2, title: '文本研读', duration: 15, content: '逐段分析论证结构，标注比喻论证和对比论证。使用原版体会荀子文风。', ancientTextRef: 'text-011', tier: 'original', activities: ['逐段分析', '标注论证方法'] },
      { order: 3, title: '考点归纳', duration: 10, content: '归纳"而""于""之"等虚词用法，结合白话解读版对照理解', ancientTextRef: 'text-011', tier: 'vernacular', activities: ['归纳总结', '真题链接'] },
      { order: 4, title: '拓展应用', duration: 8, content: '仿写一段比喻论证，话题"读书"', activities: ['写作练习', '互评'] },
    ],
    createdAt: '2025-03-14',
    authorId: 'teacher-002',
    isPublic: true,
    downloads: 234,
    tags: ['高考备考', '文言文', '论证方法', '荀子'],
  },
];

// ---- 教师端统计 ----
export const mockTeachingStats: TeachingStats = {
  totalLessonPlans: 48,
  publicLessonPlans: 32,
  totalDownloads: 1286,
  popularPlans: [
    { id: 'plan-003', title: '《劝学》论证方法分析——高考文言文备考', downloads: 234 },
    { id: 'plan-001', title: '《静夜思》古诗教学教案', downloads: 156 },
    { id: 'plan-002', title: '《岳阳楼记》精读教案', downloads: 89 },
  ],
  recentPlans: [],
};

// ---- 研学任务 ----
export const mockStudyTasks: StudyTask[] = [
  {
    id: 'task-001', title: '唐诗中的月亮意象研学',
    description: '通过阅读《静夜思》等唐诗，探索古人如何用月亮表达情感',
    targetGrade: [3, 4], textIds: ['text-001'],
    exercises: [
      { id: 'ex-001', type: 'choice', question: '《静夜思》中"疑是地上霜"的"疑"是什么意思？', options: ['怀疑', '好像', '疑问', '奇怪'], answer: '好像', analysis: '"疑"在这里是"好像、仿佛"的意思。', difficulty: 1 },
    ],
    createdAt: '2025-01-15', assignedCount: 45, completedCount: 38,
  },
  {
    id: 'task-002', title: '寓言故事中的智慧',
    description: '阅读《守株待兔》等寓言，理解古人的处世智慧',
    targetGrade: [3, 4, 5], textIds: ['text-003'],
    exercises: [
      { id: 'ex-002', type: 'short_answer', question: '请用自己的话说说"守株待兔"告诉我们什么道理？', answer: '不能死守经验，要主动努力。', analysis: '考查对寓言寓意的理解。', difficulty: 2 },
    ],
    createdAt: '2025-02-10', assignedCount: 60, completedCount: 42,
  },
  {
    id: 'task-003', title: '《岳阳楼记》深度研学——家国情怀',
    description: '精读《岳阳楼记》，探究范仲淹的政治理想与文学成就',
    targetGrade: [8, 9], textIds: ['text-007'],
    exercises: [
      { id: 'ex-003', type: 'essay', question: '结合课文，谈谈你对"先天下之忧而忧，后天下之乐而乐"的理解（200字）', answer: '围绕家国情怀、责任担当展开。', analysis: '考查文言文理解深度和论述能力。', difficulty: 3 },
    ],
    createdAt: '2025-03-01', assignedCount: 35, completedCount: 28,
  },
];

// ---- 学情统计 ----
export const mockLearningStats: LearningStats = {
  totalStudents: 328,
  activeStudents: 256,
  totalReadingTime: 86400,
  avgAccuracy: 76.8,
  popularTexts: [
    { textId: 'text-001', title: '静夜思', readCount: 212 },
    { textId: 'text-007', title: '岳阳楼记', readCount: 178 },
    { textId: 'text-011', title: '劝学', readCount: 145 },
  ],
  gradeDistribution: [
    { grade: 1, count: 28 }, { grade: 2, count: 32 }, { grade: 3, count: 35 },
    { grade: 4, count: 34 }, { grade: 5, count: 31 }, { grade: 6, count: 28 },
    { grade: 7, count: 30 }, { grade: 8, count: 35 }, { grade: 9, count: 25 },
    { grade: 10, count: 22 }, { grade: 11, count: 18 }, { grade: 12, count: 10 },
  ],
  weeklyTrend: [
    { date: '03-10', readingCount: 85 }, { date: '03-11', readingCount: 102 },
    { date: '03-12', readingCount: 78 }, { date: '03-13', readingCount: 121 },
    { date: '03-14', readingCount: 95 }, { date: '03-15', readingCount: 72 },
    { date: '03-16', readingCount: 108 },
  ],
};

// ---- 生字注释数据 ----
export const mockStudyPoints: Record<string, StudyPoint[]> = {
  'text-001': [
    { char: '疑', pinyin: 'yí', explanation: '好像、仿佛', radical: '疋', strokes: 14 },
    { char: '霜', pinyin: 'shuāng', explanation: '水汽凝结的白色冰晶', radical: '雨', strokes: 17 },
    { char: '举', pinyin: 'jǔ', explanation: '抬起、向上', radical: '丶', strokes: 9 },
    { char: '思', pinyin: 'sī', explanation: '思念、想念', radical: '心', strokes: 9 },
  ],
  'text-002': [
    { char: '善', pinyin: 'shàn', explanation: '善良、美好', radical: '口', strokes: 12 },
    { char: '苟', pinyin: 'gǒu', explanation: '如果、假如', radical: '艹', strokes: 8 },
    { char: '迁', pinyin: 'qiān', explanation: '改变、迁移', radical: '辶', strokes: 6 },
  ],
  'text-003': [
    { char: '株', pinyin: 'zhū', explanation: '树桩', radical: '木', strokes: 10 },
    { char: '释', pinyin: 'shì', explanation: '放下', radical: '釆', strokes: 12 },
    { char: '冀', pinyin: 'jì', explanation: '希望', radical: '八', strokes: 16 },
    { char: '走', pinyin: 'zǒu', explanation: '跑（古今异义）', radical: '走', strokes: 7 },
  ],
  'text-004': [
    { char: '鉴', pinyin: 'jiàn', explanation: '镜子', radical: '金', strokes: 13 },
    { char: '渠', pinyin: 'qú', explanation: '它，指池塘', radical: '水', strokes: 12 },
    { char: '徘徊', pinyin: 'pái huái', explanation: '来回移动', radical: '彳', strokes: 12 },
  ],
  'text-006': [
    { char: '庐', pinyin: 'lú', explanation: '简陋的房屋', radical: '广', strokes: 7 },
    { char: '挂', pinyin: 'guà', explanation: '悬挂', radical: '扌', strokes: 9 },
    { char: '疑', pinyin: 'yí', explanation: '怀疑、好像', radical: '疋', strokes: 14 },
  ],
  'text-007': [
    { char: '谪', pinyin: 'zhé', explanation: '贬官降职', radical: '讠', strokes: 13 },
    { char: '属', pinyin: 'zhǔ', explanation: '通"嘱"，嘱咐', radical: '尸', strokes: 12 },
    { char: '衔', pinyin: 'xián', explanation: '含着', radical: '彳', strokes: 11 },
    { char: '晖', pinyin: 'huī', explanation: '阳光', radical: '日', strokes: 10 },
  ],
  'text-008': [
    { char: '崩殂', pinyin: 'bēng cú', explanation: '帝王去世', radical: '山/歹', strokes: 11 },
    { char: '卑鄙', pinyin: 'bēi bǐ', explanation: '身份低微（古今异义）', radical: '十/亠', strokes: 8 },
    { char: '驽钝', pinyin: 'nú dùn', explanation: '才能低下', radical: '马/钅', strokes: 8 },
  ],
  'text-009': [
    { char: '缘', pinyin: 'yuán', explanation: '沿着', radical: '纟', strokes: 12 },
    { char: '舍', pinyin: 'shě', explanation: '放弃、丢下', radical: '舌', strokes: 8 },
    { char: '要', pinyin: 'yāo', explanation: '通"邀"，邀请', radical: '覀', strokes: 9 },
    { char: '志', pinyin: 'zhì', explanation: '做标记', radical: '心', strokes: 7 },
  ],
  'text-010': [
    { char: '属', pinyin: 'zhǔ', explanation: '劝酒', radical: '尸', strokes: 12 },
    { char: '冯', pinyin: 'píng', explanation: '通"凭"，凭借', radical: '冫', strokes: 5 },
    { char: '嫠', pinyin: 'lí', explanation: '寡妇', radical: '女', strokes: 14 },
    { char: '愀然', pinyin: 'qiǎo rán', explanation: '神色变得严肃', radical: '忄', strokes: 12 },
  ],
  'text-011': [
    { char: '輮', pinyin: 'róu', explanation: '通"煣"，用火烤使弯曲', radical: '车', strokes: 16 },
    { char: '跬', pinyin: 'kuǐ', explanation: '半步', radical: '足', strokes: 13 },
    { char: '锲', pinyin: 'qiè', explanation: '用刀刻', radical: '钅', strokes: 14 },
    { char: '镂', pinyin: 'lòu', explanation: '雕刻', radical: '钅', strokes: 14 },
  ],
  'text-012': [
    { char: '受', pinyin: 'shòu', explanation: '通"授"，传授', radical: '又', strokes: 8 },
    { char: '庸', pinyin: 'yōng', explanation: '难道、哪里', radical: '广', strokes: 11 },
    { char: '贻', pinyin: 'yí', explanation: '赠送', radical: '贝', strokes: 9 },
    { char: '句读', pinyin: 'jù dòu', explanation: '文章的断句停顿', radical: '勹/讠', strokes: 5 },
  ],
  'text-013': [
    { char: '惠', pinyin: 'huì', explanation: '通"慧"，聪明', radical: '心', strokes: 12 },
    { char: '诣', pinyin: 'yì', explanation: '拜访', radical: '讠', strokes: 8 },
    { char: '乃', pinyin: 'nǎi', explanation: '于是、就', radical: '丿', strokes: 2 },
    { char: '禽', pinyin: 'qín', explanation: '鸟（古义，这里指鸟类的统称）', radical: '人', strokes: 12 },
  ],
  'text-014': [
    { char: '鬻', pinyin: 'yù', explanation: '卖', radical: '鬲', strokes: 22 },
    { char: '誉', pinyin: 'yù', explanation: '夸耀、称赞', radical: '言', strokes: 13 },
    { char: '陷', pinyin: 'xiàn', explanation: '刺穿、穿透', radical: '阝', strokes: 10 },
    { char: '或', pinyin: 'huò', explanation: '有人（古今异义，今义"或者"）', radical: '戈', strokes: 8 },
    { char: '弗', pinyin: 'fú', explanation: '不', radical: '弓', strokes: 5 },
  ],
  'text-015': [
    { char: '数', pinyin: 'shuò', explanation: '多次、屡次', radical: '攵', strokes: 13 },
    { char: '驰逐', pinyin: 'chí zhú', explanation: '赛马', radical: '马/辶', strokes: 6 },
    { char: '弟', pinyin: 'dì', explanation: '通"第"，只管、尽管', radical: '丷', strokes: 7 },
    { char: '然', pinyin: 'rán', explanation: '认为……对（意动用法）', radical: '灬', strokes: 12 },
  ],
  'text-016': [
    { char: '鼓', pinyin: 'gǔ', explanation: '弹奏（乐器）', radical: '鼓', strokes: 13 },
    { char: '善哉', pinyin: 'shàn zāi', explanation: '真好啊（感叹结构）', radical: '口/口', strokes: 12 },
    { char: '汤汤', pinyin: 'shāng shāng', explanation: '水势浩大的样子', radical: '氵', strokes: 6 },
    { char: '绝', pinyin: 'jué', explanation: '弄断', radical: '纟', strokes: 9 },
  ],
  'text-017': [
    { char: '处士', pinyin: 'chǔ shì', explanation: '有才德而隐居不仕的人', radical: '夂/士', strokes: 5 },
    { char: '曝', pinyin: 'pù', explanation: '晒', radical: '日', strokes: 19 },
    { char: '股', pinyin: 'gǔ', explanation: '大腿（古今异义，今义"屁股"）', radical: '月', strokes: 8 },
    { char: '掉', pinyin: 'diào', explanation: '摇动、甩（古今异义，今义"落下"）', radical: '扌', strokes: 11 },
  ],
  'text-018': [
    { char: '弈', pinyin: 'yì', explanation: '下棋（专指围棋）', radical: '廾', strokes: 9 },
    { char: '诲', pinyin: 'huì', explanation: '教导', radical: '讠', strokes: 9 },
    { char: '鸿鹄', pinyin: 'hóng hú', explanation: '天鹅', radical: '氵/鸟', strokes: 11 },
    { char: '援', pinyin: 'yuán', explanation: '拉、引（弓）', radical: '扌', strokes: 12 },
    { char: '弗若', pinyin: 'fú ruò', explanation: '不如', radical: '弓/艹', strokes: 5 },
  ],
  'text-019': [
    { char: '去', pinyin: 'qù', explanation: '距离（古今异义，今义"前往"）', radical: '厶', strokes: 5 },
    { char: '及', pinyin: 'jí', explanation: '到了', radical: '又', strokes: 3 },
    { char: '汤', pinyin: 'tāng', explanation: '热水（古今异义，今义"菜汤"）', radical: '氵', strokes: 6 },
    { char: '知', pinyin: 'zhī', explanation: '通"智"，智慧', radical: '矢', strokes: 8 },
    { char: '决', pinyin: 'jué', explanation: '判断、裁决', radical: '冫', strokes: 6 },
  ],
  'text-020': [
    { char: '恭勤', pinyin: 'gōng qín', explanation: '恭敬勤勉', radical: '小/力', strokes: 10 },
    { char: '通', pinyin: 'tōng', explanation: '通晓', radical: '辶', strokes: 10 },
    { char: '练囊', pinyin: 'liàn náng', explanation: '用白绢做的袋子', radical: '纟/口', strokes: 8 },
    { char: '盛', pinyin: 'chéng', explanation: '装', radical: '皿', strokes: 11 },
  ],
  'text-021': [
    { char: '世传', pinyin: 'shì chuán', explanation: '世人传说', radical: '一/亻', strokes: 5 },
    { char: '是', pinyin: 'shì', explanation: '这（古今异义，今义"判断动词"）', radical: '日', strokes: 9 },
    { char: '老媪', pinyin: 'lǎo ǎo', explanation: '老妇人', radical: '耂/女', strokes: 6 },
    { char: '卒业', pinyin: 'zú yè', explanation: '完成学业', radical: '十/业', strokes: 8 },
  ],
  'text-022': [
    { char: '知', pinyin: 'zhī', explanation: '通"智"，智慧（末字）', radical: '矢', strokes: 8 },
    { char: '敏', pinyin: 'mǐn', explanation: '聪敏、机敏', radical: '攵', strokes: 11 },
    { char: '好', pinyin: 'hào', explanation: '喜爱', radical: '女', strokes: 6 },
    { char: '耻', pinyin: 'chǐ', explanation: '以……为耻（意动用法）', radical: '耳', strokes: 10 },
    { char: '厌', pinyin: 'yàn', explanation: '满足（古今异义，今义"讨厌"）', radical: '厂', strokes: 6 },
  ],
  'text-023': [
    { char: '余', pinyin: 'yú', explanation: '我', radical: '人', strokes: 7 },
    { char: '漫浪', pinyin: 'màn làng', explanation: '随便、马虎', radical: '氵/氵', strokes: 11 },
    { char: '决', pinyin: 'jué', explanation: '一定', radical: '冫', strokes: 6 },
    { char: '急', pinyin: 'jí', explanation: '紧要、重要（古今异义，今义"着急"）', radical: '心', strokes: 9 },
    { char: '岂', pinyin: 'qǐ', explanation: '难道', radical: '山', strokes: 6 },
  ],
  'text-024': [
    { char: '盖', pinyin: 'gài', explanation: '发语词，无实义', radical: '艹', strokes: 11 },
    { char: '士人', pinyin: 'shì rén', explanation: '读书人', radical: '士/人', strokes: 3 },
    { char: '识', pinyin: 'shí', explanation: '见识', radical: '讠', strokes: 7 },
    { char: '恒', pinyin: 'héng', explanation: '恒心、毅力', radical: '忄', strokes: 9 },
    { char: '断', pinyin: 'duàn', explanation: '绝对、一定', radical: '斤', strokes: 11 },
  ],
};

// ---- 阅读记录 ----
export const mockReadingRecords: ReadingRecord[] = [
  { id: 'rec-001', studentId: 'student-001', textId: 'text-001', tier: 'adapted', progress: 100, timeSpent: 180, exercisesCompleted: 3, exercisesCorrect: 3, lastReadAt: '2025-03-16T14:30:00' },
  { id: 'rec-002', studentId: 'student-001', textId: 'text-003', tier: 'vernacular', progress: 100, timeSpent: 420, exercisesCompleted: 5, exercisesCorrect: 4, lastReadAt: '2025-03-15T10:00:00' },
  { id: 'rec-003', studentId: 'student-001', textId: 'text-007', tier: 'adapted', progress: 60, timeSpent: 540, exercisesCompleted: 2, exercisesCorrect: 2, lastReadAt: '2025-03-14T16:00:00' },
];
